# Generated by Django 4.1.5 on 2023-01-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsForVolunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('check_agreement', models.BooleanField(verbose_name='Приняты условия пользовательского соглашения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Заявка на волонтера',
                'verbose_name_plural': 'Заявки на волонтера',
            },
        ),
        migrations.CreateModel(
            name='FeedBackSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('message', models.TextField(unique=True, verbose_name='Сообщение/Предложение')),
                ('check_agreement', models.BooleanField(verbose_name='Приняты условия пользовательского соглашения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Сообщение/Предложение',
                'verbose_name_plural': 'Сообщения/Предложения',
            },
        ),
        migrations.CreateModel(
            name='RegistrationForEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('check_agreement', models.BooleanField(verbose_name='Приняты условия пользовательского соглашения')),
                ('event_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations',
                                   to='event.eventmodel')),
            ],
            options={
                'verbose_name': 'Регистрация на мероприятие',
                'verbose_name_plural': 'Регистрации на мероприятия',
            },
        ),
        migrations.AddConstraint(
            model_name='registrationforevents',
            constraint=models.UniqueConstraint(fields=('phone', 'event_id'), name='constraint_unique'),
        ),
    ]
