# Generated by Django 3.2.16 on 2023-02-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('forms_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrationforevents',
            name='constraint_unique',
        ),
        migrations.AlterUniqueTogether(
            name='registrationforevents',
            unique_together={('phone', 'event_id')},
        ),
    ]
