# Generated by Django 3.2.16 on 2022-12-11 07:46


from django.db import migrations, models
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('body', models.TextField(verbose_name='Отзыв')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
            bases=(models.Model, utils.mixins.ReprMixin),
        ),
    ]
