# Generated by Django 3.2.16 on 2023-01-24 20:51



from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Наименование')),
                ('address', models.TextField(verbose_name='Адрес проведения')),
                ('time', models.DateTimeField(verbose_name='Время проведения')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='PhotoEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Выберите изображение', upload_to='media/event/%Y/%m/%d/', verbose_name='фото с мероприятия')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_images', to='event.eventmodel')),
            ],
            options={
                'verbose_name': 'Фотография с мероприятия',
                'verbose_name_plural': 'Фотографии с мероприятия',
            },
        ),
    ]
