# Generated by Django 3.2.16 on 2023-01-18 05:55

from django.db import migrations, models
import utils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/company_logos/%Y/%m/%d/', verbose_name='Логотип')),
                ('title', models.TextField(verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Чем была полезна')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
            bases=(models.Model, utils.mixins.ReprMixin),
        ),
    ]
